### PR TITLE
Generic help

### PR DESCRIPTION
**Pull request by alexbruy**
Backport of the generic help system from QGIS 3.0

### CODE REVIEW

**Comment by dakcarto** [comment]
Hi @alexbruy. Any ideas on the Travis failure?
https://dash.orfeo-toolbox.org/viewBuildError.php?buildid=262548

**Comment by dakcarto** [comment]
Closing/reopening to re-trigger Travis CI.

**Comment by dakcarto** [comment]
Re-ran Travis CI against 2.18.4 and got same error:
https://dash.orfeo-toolbox.org/viewBuildError.php?buildid=262611

**Comment by alexbruy** [comment]
Fixed now

**Pull request merged**
